# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1133eaa6d3eab0566991a90622eea9767081dbd74bde1be3ba619c4da565c238fa3470648be7758b4a35100d0c47640b31ae14ec27c4d7d942ba1f3f726715a

test:
  secret_key_base: 7dd1af39adeef055d0cd57bb6a93b911694bb8626af42c878aaad676d7b6c29d50b52908c3b77714da966aeece95221b4819825070f8db77b9d13fb020566dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
